### ISSUE TITLE
Misuse of “i.e.” in two messages

### ISSUE THREAD

**Issue by McDutchie** [ProfessionalWiki/WikibaseExport#178]
In the following two messages, “i.e.” should be “e.g.”, because what follows is clearly an example of a property ID/label.

* URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=wikibase-export-config-header-id&group=mwgithub-wikibaseexport&language=nl
* URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=wikibase-export-config-header-label&group=mwgithub-wikibaseexport&language=nl

See also: https://www.merriam-webster.com/grammar/ie-vs-eg-abbreviation-meaning-usage-difference

**Comment by JeroenDeDauw** [comment]
PR weclome

**Comment by McDutchie** [comment]
Sorry but I'm not going to spend half an hour messing with a PR when the maintainer could fix the typos in about two minutes. Fix them or don't; I've done my bit.
