### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by kghbln** [ProfessionalWiki/WikibaseExport#180]
See failures on https://github.com/ProfessionalWiki/WikibaseExport/pull/179

**Comment by malberts** [comment]
This was a temporary issue with Phabricator checkout. Apparently it was rate limiting us (error code 429.

I reran the last 2 CI runs and all of the jobs passed:
https://github.com/ProfessionalWiki/WikibaseExport/actions/runs/9677503889
https://github.com/ProfessionalWiki/WikibaseExport/actions/runs/9677550809
