### ISSUE TITLE
Add "Company properties" support

### ISSUE THREAD

**Issue by malberts** [ProfessionalWiki/WikibaseExport#31]
The "Select variables" section needs to show all the available properties applicable to companies. This must exclude properties that are not used on companies. Searching can filter the properties shown in the list, but the user needs to be able to scroll down without searching.

AC:
* Define list of "company property" IDs in LocalSettings
* These properties need to be retrieved so that the list of names can be displayed on the export form
* User cannot search/select a property that is not a company property
* Searching does not perform web request. It just filters the predefined list.

**Comment by malberts** [comment]
The UI starts to become a bit cluttered once you start selecting "all" things. One of the bigger Wikibase instances we discussed has ~80 properties.

![image](https://user-images.githubusercontent.com/1428594/201085222-0294cfc5-fa1a-4a9a-9517-3314e2718eba.png)

**Comment by JeroenDeDauw** [comment]
> Add special page, like Mediawiki:WikibaseExportProperties, to define/add to properties in LocalSettings

Better use `Mediawiki:WikibaseExport`, so we can add other config on there as well

**Comment by malberts** [comment]
If we're going to use that message page for other config, does that mean we're going to need JSON storage and a custom UI?
